// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PDFRepositoryProject.Data;
using System;

namespace PDFRepositoryProject.Migrations
{
    [DbContext(typeof(PDFContext))]
    [Migration("20181227214128_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PDFRepositoryProject.Models.DbPDFDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("UploadDateTime");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PDFRepositoryProject.Models.PDFFileData", b =>
                {
                    b.Property<int>("Id");

                    b.Property<byte[]>("Content");

                    b.HasKey("Id");

                    b.ToTable("PDFFileData");
                });

            modelBuilder.Entity("PDFRepositoryProject.Models.PDFFileData", b =>
                {
                    b.HasOne("PDFRepositoryProject.Models.DbPDFDocument", "DbPDFDocument")
                        .WithOne("Data")
                        .HasForeignKey("PDFRepositoryProject.Models.PDFFileData", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
